### PR TITLE
Utilize priority queue for BFS -> Dijkstra's algorithm

### PR DESCRIPTION
**Pull request by tbeu**
Otherwise performance of BFS with FIFO queue is far too bad for complicated puzzles.

Unfortunately, there now is duplicated code for the two solve methods.

### CODE REVIEW

**Comment by tbeu** [comment]
Let me know if you still want to keep the BFS with FIFO queue and have BFS with priority queue as third algorithm instead.

**Comment by karakanb** [comment]
I'd appreciate if you can create it as a third algorithm instead, that way it'd be way easier to merge these changes. Hopefully, that version of the PR shouldn't touch any of the existing algorithms.

**Comment by tbeu** [comment]
Sure, I updated the PR.

Note, that I also fixed the visitor check for both BFS and DFS by adding

```c++
this->pastSteps[tempBoard.identifier] = tempBoard;
```

Not having this line leads to far too many board evaluations (and was the root cause why BFS did not terminate for complicated puzzles).

**Review by karakanb — APPROVED** [review]

**Comment by karakanb** [comment]
This is a cool improvement, thanks for fixing the bug and contributing the new algorithm!

**Pull request merged**
